/*
 * Copyright 2024 Daraja Multiplatform
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vickbt.darajakmp.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param [originatorConversationID] Unique identifier of the request message that is auto-generated by M-PESA for a third party/Organization and it can be used to check the status of the transaction.
 * @param [conversationID] Unique identifier generated by M-Pesa for a previous request message. It is used to support communication multi-times between the third party and M-Pesa for one operation/transaction.
 * @param [responseCode] Indicates whether Mobile Money accepts the request or not.
 * @param [responseDescription] Description of the [responseCode].
 * */
@Serializable
data class AccountBalanceResponse(
    @SerialName("OriginatorConversationID")
    val originatorConversationID: String,

    @SerialName("ConversationID")
    val conversationID: String,

    @SerialName("ResponseCode")
    val responseCode: String,

    @SerialName("ResponseDescription")
    val responseDescription: String
)
