package com.vickbt.darajakmp.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param [originatorConversationID] Unique identifier of the request message that is auto-generated by M-PESA for a third party/Organization and it can be used to check the status of the transaction.
 * @param [conversationID] Unique identifier generated by M-Pesa for a previous request message. It is used to support communication multi-times between the third party and M-Pesa for one operation/transaction.
 * @param [responseCode] Indicates whether Mobile Money accepts the request or not.
 * @param [responseDescription] Description of the [responseCode].
 * */
@Serializable
data class B2CResponse(
    @SerialName("ConversationID")
    val conversationID: String,

    @SerialName("OriginatorConversationID")
    val originatorConversationID: String,

    @SerialName("ResponseCode")
    val responseCode: String,

    @SerialName("ResponseDescription")
    val responseDescription: String
)
