name: Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: 00 00 30 * * # At 00:00 on 30th every month

jobs:

  dependency-update:
    name: 🔭 Check for dependencies update
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check for release dependencies
        run: ./gradlew :daraja:dependencyUpdates -Drevision=release -DoutputFormatter=html -DreportfileName=dependencies_report --stacktrace

      - name: Upload dependencies report artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dependency Report
          path: daraja/build/reports/dependencies_report.html