name: Create and Publish Swift Package

on:
  workflow_dispatch:

jobs:
  build:
    name: 🔨 Build & Publish
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build iOS framework
        id: buildPackage
        run: ./gradlew createSwiftPackage --stacktrace

      - name: Upload Swift Package directory
        uses: actions/upload-artifact@v3
        with:
          name: swiftpackage
          path: daraja/swiftpackage
          retention-days: 1

      - name: Display structure of downloaded files
        run: ls -R

      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'swiftpackage'
          destination-github-username: 'VictorKabata'
          destination-repository-name: 'DarajaSwiftPackage'
          create-target-branch-if-needed: true
